[development]
address = "localhost"
port = 43201
workers = 8
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 43201
workers = 8
log = "normal"
limits = { forms = 32768 }